---
repo-name: peripherals-pardot
categories:
- Messaging
display-name: Pardot
manufacture: Pardot
product: 
description: Pardot B2B marketing automation by Salesforce helps marketers create
  more leads, generate more pipeline, and empower sales to close more deals.
thumbnail: thumbnail.png
